/*
 * AI-Provenance:
 *   model: Claude Opus 5
 *   harness: Cursor
 */
// GENERATED by scripts/flutter-examples.mjs — run `npm run examples:generate`.
//
// Committed so that `next build` can tell a stale bundle from a fresh one
// without having the Flutter SDK available. `npm run examples:check` fails
// the build when this drifts from the MDX.

export interface FlutterExample {
  /** The widget the island mounts. */
  preview: string
  /** Pages the snippet appears on, for error messages. */
  docs: string[]
  /** Docs-only `Docs*` widgets the snippet uses, if any. */
  helpers?: string[]
}

export const flutterExamples: Record<string, FlutterExample> = {
  "e1be7cae35e2": { preview: "SignupForm", docs: ["first-form.mdx"] },
  "e2e19281cb1f": { preview: "PasswordForm", docs: ["validation.mdx"], helpers: ["DocsTextField"] },
}
